FROM spark_base:latest

# Initiate Spark master
CMD ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]

RUN apt install libmysqlclient-dev libssl-dev libkrb5-dev libsasl2-dev libffi-dev libpq-dev libldap2-dev -y
