FROM spark_base:latest

# Set environment variables for the Spark worker
ENV SPARK_WORKER_CORES 1
ENV SPARK_WORKER_MEMORY 1g

# Set SPARK_MASTER environment variable in Docker Compose or pass directly.
CMD ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://master:7077"]
